### ISSUE TITLE
ALVR Doesn't detect steamvr (Linux)

### ISSUE THREAD

**Issue by zortos293** [alvr-org/ALVR#1162]
## Description

When i launch alvr it shows me steamvr isent installed 

i'm using the flatpak version of steamvr

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=8d314e1557

**CPU**:
11th Gen Intel i5-11400H (12) @ 4.500GHz

**GPU**:
NVIDIA GeForce RTX 3060 Mobile / Max-Q < Main GPU
Intel TigerLake-H GT1 [UHD Graphics]

**Audio**:
Tiger Lake-H HD Audio Controller

### Installation
**ALVR Version**:
v18.2.3

**SteamVR Version**:
Version 1.24.1 Beta

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Fedora Linux 36 (Workstation Edition)

**Comment by yingtian991221** [comment]
Got exactly the same issue on Ubuntu 20.04, building it myself

**Comment by yingtian991221** [comment]
> Got exactly the same issue on Ubuntu 20.04, building it myself

Solved now. I think the first thing is to sudo ./alvr_launcher, with sudo alvr can access steamVR and install drivers automatically, then reboot will solve most of the problem. Good luck!

**Comment by chowned** [comment]
Can you check with "Flatseal" to see if you have permissions to find the folder? Trying to guess, but flatpak has always this problem..

**Comment by mossymossmoss** [comment]
@yingtian991221 can you please go into more detail on how you got it working? I have run the launcher with sudo but I am still failing to detect my Steam VR installation

**Comment by yingtian991221** [comment]
> 

Sorry for the late reply, in case you or others who still need to solve this problem, I just rebooted my computer once after changing settings many times, and reboot solved the whole problem. I think reboot made some configuration applied so SteamVR is detected now.

**Comment by Sewdohe** [comment]
> > 
> 
> Sorry for the late reply, in case you or others who still need to solve this problem, I just rebooted my computer once after changing settings many times, and reboot solved the whole problem. I think reboot made some configuration applied so SteamVR is detected now.

Changed settings where? I'm having the same issue and I can't get steam (runtime/native) to launch games hardly at all

**Comment by IlogicalKarma** [comment]
In my case 2 addons where blocked by steamvr due to a crash. If anyone else has this issue, check the steamvr settings
