### ISSUE TITLE
SteamVR crash with Half-Life: Alyx

### ISSUE THREAD

**Issue by GhostNaN** [alvr-org/ALVR#1534]
## Description

When reloading the shotgun in Half-Life: Alyx
SteamVR will hard crash (SEGV) while the game is still running.
This issue is 100% replicable and only occurs after this commit: https://github.com/alvr-org/ALVR/commit/617b4670ee10b9e6b24642a9e454ed5fe2e290fe

## Troubleshooting
Realizing that the only thing that was the same with the shotgun, was the haptic feedback.
I was able to narrow down this issue fairly easily.

I have also tried disabling haptic feedback in the settings, but it made no difference.  

There wasn't much in the steamvr logs because it was a hard crash, but ALVR had this to say:
```What happened: panicked at 'can not convert float seconds to Duration: value is negative', /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/time.rs:780:23 Backtrace: 0: 1: 2: 3: 4: 5: 6: 7: 8: 9: _ZN9CVRServer8RunFrameEv 10: _ZN9CVRServer3RunEv 11: _Z8RealMainjR19VRServerArguments_t 12: main 13: 14: __libc_start_main 15: _start```

Let me know if you need anything else.
### Hardware
Here are my pc specs: https://linux-hardware.org/?probe=29ec74ac8b
Quest 2

**SteamVR Version**:
1.25.7

**Comment by zarik5** [comment]
Thank you, I take a look.

**Comment by zarik5** [comment]
I pushed a fix, let me know it it works.

**Comment by GhostNaN** [comment]
This: https://github.com/alvr-org/ALVR/commit/d2576299022307ba7fe66a8539c42f784df58322
Didn't fix the issue unfortunately.
With the exact same results and error.
