### ISSUE TITLE
when turning off the headset‘s screen and then turn on it, ALVR will be stuck.

### ISSUE THREAD

**Issue by Terrificia** [alvr-org/ALVR#782]
#### Environement

What hardware do you have: geforce gtx 950m
This issue appears on ALVR 16.0.0, 15.2.1 doesn't appear
quest2 version 32.xx

**Comment by polyjitter** [comment]
Same issue here. Also occurs when turning onn passthrough. Gets to "connecting to stream" then freezes, as in ASW freeze, as in the frame is stick. While it crashes while already connected, it brings the application currently in use to a halt visually, though audio still functions implying its still working.

**Comment by splatpope** [comment]
getting the same exact problem

**Comment by polyjitter** [comment]
Problem is persistent in SteamVR beta and stable, and is persistent between stable, beta, and nightly builds of ALVR.

**Comment by polyjitter** [comment]
Funnily enough, if you start ALVRwith the headset screen off, but the A:VR client open, it says it's sending frame data, but as soon as you turn on the headset display, it immediately freezes.

![Image of Statistics once display is powered.](https://do-you-want-to.work-for-an.agency/31Xy5do.png)

**Comment by polyjitter** [comment]
Persistent with reinstall of both SteamVR and ALVR, as well as settings wipe.

**Comment by polyjitter** [comment]
Additionally, this will happen if you try to start the client after initializing the server. The only way to connect is to start up the server after the client, at which point it stays connected until one of the three happens:

1) The headset goes to sleep
2) The headset goes far enough outside the boundary area to pull the Quest out of the currently running app
3) Passthrough is enabled via double-tap of the headset

Like OP, this is a recent regression with ALVR. The only thing you can do once this has happened is to fully restart alvr, steamvr, and the currently running application.

**Comment by polyjitter** [comment]
Video of the issue:

[](https://www.youtube.com/watch?v=Hw2LZn8dG7Y)

**Comment by polyjitter** [comment]
```
21:42:39.608180700 [INFO] #{"id":"ClientDisconnected"}#
21:42:39.608218800 [INFO] Client disconnected. Cause: At alvr\common\src\sockets\control_socket.rs:32
21:42:40.111509600 [WARN] Handshake: At alvr\server\src\connection.rs:121: At alvr\common\src\sockets\control_socket.rs:78
21:42:41.155414400 [INFO] #{"id":"ClientConnected"}#
21:42:41.155707000 [INFO] Serial Number: 1WMGH000XX0000
21:42:41.155746100 [INFO] Model Number: Miramar
21:42:41.155762700 [INFO] Render Target: 3264 1728
21:42:41.155780600 [INFO] Seconds from Vsync to Photons: 0.005000
21:42:41.155797000 [INFO] Refresh Rate: 90
21:42:41.199312800 [INFO] Setting new IPD to: 0.063099
21:42:41.505184100 [INFO] Audio recovered
```

This is the last thing in the logs, from when I stepped out and back into the boundary. The video stream has not recovered.

**Comment by polyjitter** [comment]
```
21:42:39.608180700 [INFO] #{"id":"ClientDisconnected"}#
21:42:39.608218800 [INFO] Client disconnected. Cause: At alvr\common\src\sockets\control_socket.rs:32
21:42:40.111509600 [WARN] Handshake: At alvr\server\src\connection.rs:121: At alvr\common\src\sockets\control_socket.rs:78
21:42:41.155414400 [INFO] #{"id":"ClientConnected"}#
21:42:41.155707000 [INFO] Serial Number: redacted
21:42:41.155746100 [INFO] Model Number: Miramar
21:42:41.155762700 [INFO] Render Target: 3264 1728
21:42:41.155780600 [INFO] Seconds from Vsync to Photons: 0.005000
21:42:41.155797000 [INFO] Refresh Rate: 90
21:42:41.199312800 [INFO] Setting new IPD to: 0.063099
21:42:41.505184100 [INFO] Audio recovered
```

This is the last thing in the logs, from when I stepped out and back into the boundary. The video stream has not recovered.

**Comment by splatpope** [comment]
> Additionally, this will happen if you try to start the client after initializing the server. The only way to connect is to start up the server after the client, 

Can't confirm this, as I get some luck getting the client to work starting it after a complete restart of the server/SteamVR

>at which point it stays connected until one of the three happens:
> 
> 1. The headset goes to sleep
> 2. The headset goes far enough outside the boundary area to pull the Quest out of the currently running app
> 3. Passthrough is enabled via double-tap of the headset
> 
> Like OP, this is a recent regression with ALVR. The only thing you can do once this has happened is to fully restart alvr, steamvr, and the currently running application.

Confirming these three issues, basically anything that pulls the Quest out of the app makes it hang for good even after client restarts.

I'll be downgrading to v15 until this issue is sorted out, this is getting infuriating

**Comment by Stormwing01** [comment]
Getting the same issue here, down to the last detail.

**Comment by jellyfishhunter** [comment]
I'm also still getting this issue.

**Comment by polyjitter** [comment]
I am even still getting this issue, too. Considering the improvements coming in the future that means having to stay on a previous version is not ideal, I just gave in and bought VD. It's not perfect, I miss USB video quality, but it works. Considering I have done all I can to document this extensively and thoroughly, I have to assume this is a wontfix. I would suggest everyone else experiencing this issue consider switching to another solution, too, or make your peace with forever staying without further updates.

**Comment by CrypticCherry** [comment]
I think I have fixed it by going to the installation tab and registering the ALVR drivers.

**Comment by kekkodance** [comment]
> I think I have fixed it by going to the installation tab and registering the ALVR drivers.

does this work for others too?

**Comment by Stormwing01** [comment]
> I think I have fixed it by going to the installation tab and registering the ALVR drivers.

Sadly, this hasn't fixed the issue for me. if I switch to passthrough mode (the double tap on the side of the headset) and then go out of passthrough, everything still freezes and I have to click on "restart steamvr" to fix it.
