### ISSUE TITLE
Quest 2 Controller models offset from reality [v16.0.0]

### ISSUE THREAD

**Issue by ctaetcsh** [alvr-org/ALVR#926]
## Description
When in SteamVR, touching the controllers together presents an obvious offset from where the controllers actually are and where the models are shown. If the rings are touching, then they will clip eachother in the SteamVR view. 
I intend to follow up on this issue by providing screenshots/recordings of what I am attempting to explain. 

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 5 3600

**GPU**: Radeon RX 480 

**Audio**: Realtek HD

### Installation
**ALVR Version**: 16.0.0

**SteamVR Version**: 1.20.4

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11 Pro Build 22000.466

**Comment by sctanf** [comment]
This should be fixed in nightly version of ALVR, and v17

**Comment by ctaetcsh** [comment]
Unfortunately, after upgrading to v17 this issue still persists.

**Comment by ctaetcsh** [comment]
I recorded a video that hopefully demonstrates in a somewhat understandable way what I'm trying to describe. https://youtu.be/HjRVliTd0sg

**Comment by sctanf** [comment]
The fix is a change in the default settings. Have you tried resetting the settings, this can be done by deleting `session.json` in ALVR's installation folder.

**Comment by ctaetcsh** [comment]
That worked. Thanks.
